version: '2'
services:
  web:
    build: .
    image: alexcheng/magento
    ports:
      - "80:80"
    links:
      - db
    env_file:
      - env/env
  db:
    image: mysql:5.6.23
    env_file:
      - env/env
